### ISSUE TITLE
Setup git release workflow

### ISSUE THREAD

**Issue by matteodem** [matteodem/sounds-social#38]
create a script called `release.sh` which releases a specific version of Sounds Social

## TODO

* [x] How to version? Cool version names?
  * For feature deployments always major and otherwise minor for improvements + cool names
    * {major}.{minor}-{majorName}.{minorName}
  * Check out https://github.com/webpro/release-it#-manage-pre-releases
  * Automate it so that there's no time wasted on finding a name
* [x] Search for git release tool + make script go through process with checks
* [ ] Create git tags + release on dev environment
