### ISSUE TITLE
Eliminate context.userId checks

### ISSUE THREAD

**Issue by matteodem** [matteodem/sounds-social#40]
Do a general purpose check for graphql resolvers.

## TODO

* [x] Find a way to have a general purpose `Match.Maybe String` check (maybe context option?
 https://github.com/matteodem/sounds-social/blob/master/code/api/server/index.js#L20)
* [x] Add the check
* [x] Create requireUserId method that can be used inside collection
