### ISSUE TITLE
Check for vulnerabilities with package-scan

### ISSUE THREAD

**Issue by matteodem** [matteodem/sounds-social#42]
https://github.com/East5th/package-scan

## TODO

* [x] Update vulnerable pkgs shown by Github https://github.com/matteodem/sounds-social/network/dependencies#37225719
* [x] Fix npm warn statements on npm i
* [x] Use snyk (if trustworthy) on release for all projects https://www.npmjs.com/package/snyk
* [x] Go through source code of package-scan + snyk
* [x] Add to api app and update packages if warnings
* [x] Run one liner on release https://www.twilio.com/blog/2017/08/find-projects-infected-by-malicious-npm-packages.html or create tiny vulnerability-scanner pkg
