### ISSUE TITLE
Simplify db structure with grapher

### ISSUE THREAD

**Issue by matteodem** [matteodem/sounds-social#43]
Use https://github.com/cult-of-coders/grapher for db relations, denormalizations etc.

also check out zimme:timestampable etc. to reuse functionality

## Further links

* https://cult-of-coders.github.io/grapher/
* http://www.meteor-tuts.com/chapters/3/persistence-layer.html
* https://github.com/Herteby/graphical-grapher

## Todo

* [x] Create npm package that is similiar to join monster but for mongodb (+ useable with grapher)
  * [x] Generate fields config that is flat (so that mongodb people can also use it)
  * [x] Use https://github.com/jakepusateri/graphql-list-fields to retrieve fields
  * [x] Similiar to join monster where 4th argument (AST) is given to the helper function for selector generation (see https://github.com/graphql/graphql-js/issues/19)
  * [x] See code https://gist.github.com/matteodem/f6ee6b617b69ffb5e9ba04901b38a925
  * [x] Release + put on meteor forums
  * [x] Write in README that inspired by join monster
* [x] Update graphqlizer pkg to new API
* [x] Revert this https://github.com/matteodem/sounds-social/pull/59/files#diff-76e5d9286c366aa54b6c439e14a7f02dR6
* [x] Put requestedFields into context with `join-mongo` and use them on top level resolver
  * see https://github.com/matteodem/sounds-social/blob/master/code/api/server/index.js#L24
* [x] Clean up all methods that use graphqlizer graphqlContext method
