### ISSUE TITLE
Display followers count

### ISSUE THREAD

**Issue by matteodem** [matteodem/sounds-social#48]
For each user that listened at least 5 minutes on a profile

## TODO
* [x] Create number count component
* [x] Design in storybook (a component + in user profile)
* [x] Setup backend logic to retrieve count
* [x] Display in app
