### ISSUE TITLE
Linting + CI

### ISSUE THREAD

**Issue by matteodem** [matteodem/sounds-social#5]
Add linting step to api project for CI + update docs/Development.md

## TODO

* [x] Setup linting for API
* [x] Linting for .vue files Add https://github.com/vuejs/eslint-plugin-vue to web
* [x] Choose CI service (see #33)
* [x] Add and run `cli` command for CI (all projects)
* [x] Remove old bitbucket pipeline 
* [x] Add linting to Development.md
* [x] Display badge in README
