### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by matteodem** [matteodem/sounds-social#61]
Allow to subscribe to a newsletter on home. Just store mails in a collection for now. have some notification everytime somebody does though.

## TODO 
* [x] Create newsletter collection
* [x] Create newsletter method `addToNewsletter(email)`
* [x] Create graphql mutation `addToNewsletter`
* [x] Display input + add to newsletter button on home
* [x] Rename dir to general https://github.com/matteodem/sounds-social/tree/master/code/api/imports/api/schema/generate
* [x] Send an email every d if new newsletter signups
