### ISSUE TITLE
Cache follower counts

### ISSUE THREAD

**Issue by matteodem** [matteodem/sounds-social#69]
use https://github.com/Intellicode/graphql-resolver-cache and cache the counts in mongodb.

## TODO

* [x] Add resolver cache pkg
* [x] Setup caching logic for follower counts with lru 
* [x] Add `createMongoCache` function which returns a cache (like lru) `(cacheTimeSeconds, cacheName)`
  * always write into the same collection
  * clear the outdated cache entries every 2hrs
* [x] Create a FollowerCountCache and use that for followCount
* [x] Invalidate (see https://github.com/Intellicode/graphql-resolver-cache/issues/9#issuecomment-373816106)
