### ISSUE TITLE
Group

### ISSUE THREAD

**Issue by matteodem** [matteodem/sounds-social#7]
As an artist I want to be able to join a group so that I can showcase my collaborations with other people.

* Have a name, description, avatar image and members
* Differ from communities by being not open to join for everyone
* Can be a collective, label, duo, band etc. (customizable or pre-defined?)
* Can be subscribed to and has it's own feed (manageable by the group)

## TODO

* [x] Create Group Collection + Schema
* [x] Add GraphQL API methods (CRUD)
* [x] Make sound ownable by a group
* [x] Add group detail view
* [x] Add group management modal (similar to playlists)
* [x] Add group edit page
* [x] Add group delete button
* [x] Adjust upload sound form box to have a select box where the username is
* [x] Make group followable
* [x] Adjust feeds to display group based sounds (when followed, when part of)
* [x] Group box similar to playlist for a user
* [x] Make groups searchable
* [x] Adjust opening profile in sound player (and search for other places)
* [x] More agressively reuse components (Forms, fixme statements etc.)
* [x] Add translations
