### ISSUE TITLE
Display playCount

### ISSUE THREAD

**Issue by matteodem** [matteodem/sounds-social#70]
Display the count of "plays" for a profile (all public sounds combined).

* [x] Create a Statistic GraphQL type
* [x] Have group and user have statistic as a field
* [x] Put followerCount in there
* [x] Add playCount
* [x] Create new PlayCountCache and cache the count with it
